# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Tue Jan  8 20:38:48 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 648)
        MainWindow.setStyleSheet("background-color: #99ff99")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonDel = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDel.setGeometry(QtCore.QRect(10, 300, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.buttonDel.setFont(font)
        self.buttonDel.setStyleSheet("background-color: #f2b632")
        self.buttonDel.setObjectName("buttonDel")
        self.buttonSave = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSave.setGeometry(QtCore.QRect(310, 360, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.buttonSave.setFont(font)
        self.buttonSave.setStyleSheet("background-color: #f2b632")
        self.buttonSave.setObjectName("buttonSave")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(70, 20, 421, 251))
        self.treeWidget.setStyleSheet("background-color: #ccdcff")
        self.treeWidget.setIndentation(25)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(100)
        self.treeWidget.header().setMinimumSectionSize(50)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(620, 10, 441, 261))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(60, 50, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(260, 50, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(300, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.lastName_LE = QtWidgets.QLineEdit(self.groupBox)
        self.lastName_LE.setGeometry(QtCore.QRect(40, 70, 151, 22))
        self.lastName_LE.setStyleSheet("background-color: rgb(215, 228, 242);")
        self.lastName_LE.setObjectName("lastName_LE")
        self.IO_LE = QtWidgets.QLineEdit(self.groupBox)
        self.IO_LE.setGeometry(QtCore.QRect(40, 140, 151, 22))
        self.IO_LE.setStyleSheet("background-color: rgb(215, 228, 242);")
        self.IO_LE.setObjectName("IO_LE")
        self.Oklad_LE = QtWidgets.QLineEdit(self.groupBox)
        self.Oklad_LE.setGeometry(QtCore.QRect(260, 140, 151, 22))
        self.Oklad_LE.setStyleSheet("background-color: rgb(215, 228, 242);")
        self.Oklad_LE.setObjectName("Oklad_LE")
        self.buttonAddMember = QtWidgets.QPushButton(self.groupBox)
        self.buttonAddMember.setGeometry(QtCore.QRect(140, 180, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.buttonAddMember.setFont(font)
        self.buttonAddMember.setStyleSheet("background-color: #f2b632")
        self.buttonAddMember.setObjectName("buttonAddMember")
        self.Year_LE = QtWidgets.QLineEdit(self.groupBox)
        self.Year_LE.setGeometry(QtCore.QRect(260, 70, 151, 22))
        self.Year_LE.setStyleSheet("background-color: rgb(215, 228, 242);")
        self.Year_LE.setObjectName("Year_LE")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(620, 300, 441, 271))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(60, 50, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(300, 130, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.lastNameChange_LE = QtWidgets.QLineEdit(self.groupBox_2)
        self.lastNameChange_LE.setGeometry(QtCore.QRect(40, 70, 151, 22))
        self.lastNameChange_LE.setStyleSheet("background-color: rgb(215, 228, 242);")
        self.lastNameChange_LE.setObjectName("lastNameChange_LE")
        self.OkladChange_LE = QtWidgets.QLineEdit(self.groupBox_2)
        self.OkladChange_LE.setGeometry(QtCore.QRect(260, 150, 151, 22))
        self.OkladChange_LE.setStyleSheet("background-color: rgb(215, 228, 242);")
        self.OkladChange_LE.setObjectName("OkladChange_LE")
        self.IOChange_LE = QtWidgets.QLineEdit(self.groupBox_2)
        self.IOChange_LE.setGeometry(QtCore.QRect(40, 150, 151, 22))
        self.IOChange_LE.setStyleSheet("background-color: rgb(215, 228, 242);")
        self.IOChange_LE.setObjectName("IOChange_LE")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(50, 130, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.YearChange_LE = QtWidgets.QLineEdit(self.groupBox_2)
        self.YearChange_LE.setGeometry(QtCore.QRect(260, 70, 151, 22))
        self.YearChange_LE.setStyleSheet("background-color: rgb(215, 228, 242);")
        self.YearChange_LE.setObjectName("YearChange_LE")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(260, 50, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.buttonChangeMember = QtWidgets.QPushButton(self.groupBox_2)
        self.buttonChangeMember.setEnabled(True)
        self.buttonChangeMember.setGeometry(QtCore.QRect(140, 190, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.buttonChangeMember.setFont(font)
        self.buttonChangeMember.setStyleSheet("background-color: #f2b632")
        self.buttonChangeMember.setObjectName("buttonChangeMember")
        self.buttonGetList = QtWidgets.QPushButton(self.centralwidget)
        self.buttonGetList.setGeometry(QtCore.QRect(310, 300, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.buttonGetList.setFont(font)
        self.buttonGetList.setStyleSheet("background-color: #f2b632")
        self.buttonGetList.setObjectName("buttonGetList")
        self.buttonInfo = QtWidgets.QPushButton(self.centralwidget)
        self.buttonInfo.setGeometry(QtCore.QRect(10, 360, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.buttonInfo.setFont(font)
        self.buttonInfo.setStyleSheet("background-color: #f2b632")
        self.buttonInfo.setObjectName("buttonInfo")
        self.buttonSortOklad = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSortOklad.setGeometry(QtCore.QRect(160, 420, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.buttonSortOklad.setFont(font)
        self.buttonSortOklad.setStyleSheet("background-color: #f2b632")
        self.buttonSortOklad.setObjectName("buttonSortOklad")
        self.buttonSortName = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSortName.setGeometry(QtCore.QRect(160, 480, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.buttonSortName.setFont(font)
        self.buttonSortName.setStyleSheet("background-color: #f2b632")
        self.buttonSortName.setObjectName("buttonSortName")
        self.buttonSortAge = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSortAge.setGeometry(QtCore.QRect(160, 540, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.buttonSortAge.setFont(font)
        self.buttonSortAge.setStyleSheet("background-color: #f2b632")
        self.buttonSortAge.setObjectName("buttonSortAge")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.buttonDel, QtCore.SIGNAL("clicked()"), self.treeWidget.clearSelection)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.buttonDel.setText(QtWidgets.QApplication.translate("MainWindow", "Удалить сотрудника", None, -1))
        self.buttonSave.setText(QtWidgets.QApplication.translate("MainWindow", "Сохранить", None, -1))
        self.treeWidget.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Фамилия", None, -1))
        self.treeWidget.headerItem().setText(1, QtWidgets.QApplication.translate("MainWindow", "Инициалы", None, -1))
        self.treeWidget.headerItem().setText(2, QtWidgets.QApplication.translate("MainWindow", "Год рождения", None, -1))
        self.treeWidget.headerItem().setText(3, QtWidgets.QApplication.translate("MainWindow", "Оклад", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Данные пользователя", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Инициалы", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Фамилия ", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Год рождения", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Оклад", None, -1))
        self.buttonAddMember.setText(QtWidgets.QApplication.translate("MainWindow", "Добавить", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Изменить данные", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Фамилия ", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Оклад", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Инициалы", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Год рождения", None, -1))
        self.buttonChangeMember.setText(QtWidgets.QApplication.translate("MainWindow", "Изменить", None, -1))
        self.buttonGetList.setText(QtWidgets.QApplication.translate("MainWindow", "Добавить в таблицу", None, -1))
        self.buttonInfo.setText(QtWidgets.QApplication.translate("MainWindow", "Вывод информации", None, -1))
        self.buttonSortOklad.setText(QtWidgets.QApplication.translate("MainWindow", "Сортировка по окладу", None, -1))
        self.buttonSortName.setText(QtWidgets.QApplication.translate("MainWindow", "Сортировка по имени", None, -1))
        self.buttonSortAge.setText(QtWidgets.QApplication.translate("MainWindow", "Сортировка по возрасту", None, -1))

